workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
      - name: Set iOS deployment target to 12.0
        script: |
          cd ios
          if [ ! -f "Podfile" ]; then
            pod init
          fi
          sed -i '' 's/platform :ios, .*/platform :ios, '\''12.0'\''/' Podfile
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --simulator
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
